### ISSUE TITLE
Doesn't seem to work with Netbeans 8.2

### ISSUE THREAD

**Issue by sk33wiff** [Chris2011/nb-debugger-utils#5] opened 2016-12-14 01:53 UTC
```
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_101; Java HotSpot(TM) 64-Bit Server VM 25.101-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_101-b13
```

**Comment by markiewb** [comment] 2016-12-15 21:00
It works, but the current state of the debugger is not reflected.
Duplicate of #4?

**Comment by sk33wiff** [comment] 2016-12-15 21:28
Sorry I don't get that because even if I deactivate all breakpoints through the debug menu still doesn't work

**Comment by markiewb** [comment] 2016-12-15 21:47
The action in the Debug menu is also provided by this plugin. So it is faulty too. 
See the screencast at #4 to see the non-synchronized state.

**Comment by markiewb** [comment] 2017-01-01 11:17
I am closing this issue, because @marcelopm has not responded so far.

**Closed as completed by markiewb** 2017-01-01 11:17 UTC
Labels: invalid, question
